/-
  DE-RISK PRE-FLIGHT (STRATEGY.md §4) for the compiled C13 model.

  Goal: make `c13VerifyBody` EXECUTABLE on a REAL, valid C13 signature via the
  Verity source-semantics interpreter (`execStmtList`), using `#eval` (compiled
  evaluation — NO decide/rfl/native_decide), and check that:
    * the valid vector returns `some true`  (accept)
    * a one-byte-corrupted sig returns `some false` or `none` (reject/revert)

  Vector source: generated by the in-repo Rust CLI signer
  `signer-wasm/target/release/signer-c13` (the fast path the Forge FFI test
  `SphincsC13Test.testC13VerifyFFI_Rust` uses), for
  message = 0xdeadbeef*8. ABI-decoded to (pkSeed, pkRoot, sig=3688 B).
  This is a genuine C13 (h=22,d=2,a=19,k=7,w=8) vector, NOT the toy json.

  All scaffolding is confined to this file; Model.lean is untouched.
-/

import SphincsMinusVerifiers.Model
import Compiler.Proofs.IRGeneration.SourceSemantics

namespace SphincsMinusVerifiers.Preflight

open Compiler.CompilationModel
open Compiler.Proofs.IRGeneration.SourceSemantics

/-- The real vector, ABI-decoded. Meaningful bytes live in the HIGH 16 bytes
(top half), matching N_MASK. -/
def pkSeed : Nat := 0xffb422c71ab92bcfcf2e43999b07fe5900000000000000000000000000000000
def pkRoot : Nat := 0xd8139d907726d4207397effbef3ada3d00000000000000000000000000000000
def message : Nat := 0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef

/-- Real EVM calldata laid out as 32-byte words starting at byte 4 (the
`calldataloadWord` convention: word idx = (byteOffset-4)/32). Words 0..4 are the
ABI head (pkSeed,pkRoot,message,sigHeadOffset=0x80,sigLength=3688); words 5.. are
the 3688-byte sig padded to a 32-byte boundary. `sig.offset` = byte 164 (word 5).
This is the byte-faithful EVM image of the real transaction calldata. -/
def calldataWords : List Nat := [0xffb422c71ab92bcfcf2e43999b07fe5900000000000000000000000000000000, 0xd8139d907726d4207397effbef3ada3d00000000000000000000000000000000, 0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef, 0x80, 0xe68, 0x38eb4ba2b366484e681ff7d9703676e34e4837bbbd1285513f29fbcd0b5ea067, 0xfa85eaa528129b23af50176afdc37c5cbdf5ef23805c9692a2a662c1d264b0ce, 0xc0e8c618d040768c02e285583dc14faa972ecb0dc38c5cd43626452243998267, 0x31129b68e74213601d8da2b6c3e7fd5dbf90f308adae12d6a52c3f08dbe9c76f, 0xe1c14d227df5ee57094e69b9ff23ae032d99e89393032320bc96ae065b95ff76, 0xd8b187d501e054360246175ea78e9889cf4fa7b1e3226049fdb853d238a6bf01, 0x8723bf7e254bbdfe61bf7e952467abb74d6eb46cc9c49a55e33181bb987206e, 0x750a3a687319e002f73d2e54511b40d169aef1bb81d004295428f91829ece2cd, 0x6e792d38931bfddd876df9d653bee304918bc601831172c83da9ff5332da9b5, 0xd85444016fb0fe287eec1f23a9dea1d13b5d3ac9f7fafe74e6a66e5222c3b220, 0xd974477df06920ed591dbec00153c0a9c13a0d7b5dcb5fc2c678d6ed5755134, 0x15882f096794a428089a4f64149bfdf9fd5921e352416159c73a920437a042b5, 0x651ddad6e6975566748a25fbd3836c57bf116e54150a4bf3c9a273c9f0d34fcb, 0x53a7919d230e80e23f20de7ae04cc3c4ed5d9ff59b7e0ffaf26a7ed91df163d, 0x3d7414e682581eb62d71a477dbf220c29fb65c85d8c4f3202389f8c78c882915, 0xef448391e893e9fca1ce990df25abe69839c36ee8fd750a3a4de9a69d7a9a6cc, 0x4080802068b497a1cabf5e28b0410cdcc035a5678ddd4e828834d78af7547012, 0x77cce5618ace6c46f65a5aa1f98fdcc8aea6a9f5f5e0de32c4dd4b0df6db5f14, 0xb109cad83f43f6e595f122b78c9cde187e5701cf1d75e815586068e1d190c0cf, 0xaae81d9f8c8e057d756c8336ac267cc91a4581480d6a84bccbffcdef7d3a16b4, 0xe39a1388055eb927c234828b08bc2b99bc5f90e040b67b8669804bcb6af76a99, 0xffc72ef23cd6f602c4c4842f2374950b2d2ce613077e1942bee36c4ec568f463, 0x6ae046b393a2718a4c6376cc54f006edfbcc23f5e1cd242b467ef41f5b8e151b, 0x21b3d9e2f40afe39ddfa4750b01f62863e42c0a95fea87f3595b216d92e29401, 0xfda546898925d69e5b98d8d3d701ad99ad6d980a790d464733d1bfc7fc39bc6a, 0x646d34e822062225006f57bbcf834cbf2042627412fdbf2d5ede8a326b656863, 0x2196bcc97a7381bb428ccc5f162124f439eefa9dcbf92d6fd61bf2a464a71ec8, 0x32ce168fc98d49dcb7fd892a3c821cca92d6a63776480a53a2b4cbb7fd48d701, 0xf7ee11f23a7858eb52ac15e2c84b9c27b644e689d3e43474ea5c926ae579b8d8, 5853871822476609041752857861034802209071191889193637778748703024455873036719, 0x143a85379c1e218eb65ea9528b5d5cb8b42f939a61ce27bea260737e447345eb, 0xdfa61bd8cbf5d3ee4343721fe558fcb32b93c5d071c53509eed8b64b4a7f147a, 0x4f398eeca573db696b70bc0479b32b5cb01f16a13ae8b344d71b659e07b8ef7b, 0xc4c3681ce56a98035692fb3317ff30ab5d56df1133756a685114e6beade4606e, 0xaa7e42d8f0c9d537a9022620be9297a7bac58bb439cddd21595ff02ddca86ca3, 0xeae92a7fc70b58bbf8e3ed6e87170eee136f4d670f150666212e4783938324f9, 0x6b2b7d0041b4dc699c6ea3378ee6bc93d941e8aebbb029024ba276771591424, 0xc774289197dabe12b78900e79ec6e64fc917d73a636828cedd18d73a623a5cf5, 0xb5c425b5faf5c68a915b609cb9b74e822859b8dc65f08c9083e2be6540425fdd, 0xa3704c806ccee2536f23ea0d95830332283db96bca5c0dbe1be99e65ba97768a, 0x5ddbf74e8a04e0ca185987e87e684c7dc56c6addf45d777476e31a67687e7336, 0xbe51aa6e76cc5f37521573a6d00f1185ad45f8f2ed3a8c7c9ad09dca7f73269a, 0xc5c2eb9e2f1b775bbb8494d5ef8a37505d0096ba629103e5b3fb5fa35bd2d8c7, 0xcb43d7a61c5f3ccd1ad63ddd112fc10f1d3cb14cb47a9f80f8a3c8b3f024d636, 0x7cd44b64dcb7541abe8c4d318428a75cd3edd4fd805603e83127df5c44ea96e6, 0x989cb9f1a09f7e3d90e4967470fbdf60686c73f83f6529c3219134981880a58c, 0xb8c4bdbe5d2d59cbd05bffa391cff7ee3c642e7827b21aa8d298ec1dc633d99d, 0xb14bb64dc350136c841da8041a3750b5aa0626e1dc7826c2d966421c47c150e6, 0xa821bc10a133aceddc6cf4717c33716b07d990a284a2728138ab5b6004b4a77d, 0xdb9800ab9dcd1be6585ee0fa055cca087013d53d7c050a89522760c5101e509d, 0x1594ebc7091ce2ec1bcf9e97aae13053eab40e1f235bfe08ee81e666f91d6950, 0x1140f89648832b4515ccd0f345bbb7218ae1aec26110af13f25bc5c8ff9baac1, 0xc29bc37f7c933e405981ccd218b7e6531eba2db7d5ace5d9d6f49f0f0fe3a7c6, 0xd9c3d152bfa88858a8f1f4576f05874f65a985b4a9df7e30b012587f90fed9ca, 0x62c7ee1322c55edd12eb5448410171c3f0ad29a762c4a287ca6f0a81a12b9088, 0xc72ae5ba8f14df01cee870eec67bb20d2bf94ff53eee8d5b3dacd9ef92c95b3d, 0x4ccfb0319fefc0b4c3be24656ce8e691a4b84124bcfc97621028d55041253fbd, 0xc0876f9e3b2dff92beba08cbedc8a4ee8499c385830e7f3095efcc9d7ce7c558, 0x54bd0ca9d84f9966d614942f3f0ebba7175829ed021e14e38e4210afee750c57, 0xe336743cd3b238805f4cdae66dbf370f570fb0fa766cd20d630f1142aa1d711d, 0xf3e3c3b8155abb8c1c918b367a6179c813a1b46b4c76c134bf346a89498fb7e9, 0x70075ad4d3f94c4f140cd4188ff241409a3dc54d05e1b6a1bb0f0ad25b327907, 0x4e8b0d05365b807de157bfeb4d7451cf632917ea1dd7ed631acad795cd19f6f8, 0x45e546e8016c56baa5d9410aad09174792525b637f7bcf01f25abf9f1c7d48e7, 0x2d02d091f0ef3737174841619a870ae5b1b655faba40900ac0a8ccbf1a049dd, 0x2f96327b38b706af5f5fd484efc9bf9bd385f0079a0846e11b73a54ae9ab2b61, 0x61361c2bf132ed09b1b1d01d447fd547c9e75709ac8b2aa51b0cd4cf81814576, 0x2eb4b5752cea83d66da07050cd8c1a29327f37d84881b349a28fc502e6218ec2, 0x76e1c8af14bc4e6e42b8f436a2946a09a2d13a6e8a07a43f3d67ad8a836732f7, 0xadce7b8160668dc0918c083b54a69454b7fc8ef33049be0445ed14c072421aaf, 0x6dcd49b5c6150a2f16e0fb23120148d4fb61c79e7272bc41a2113f682b07fa6d, 0x49d13424512e9f6e6ff26347018b03c0f6a66d5db3ac00531910b609cd599749, 0xfc4c634909fd239bb867e06fb386859c533669fb526b6b7d26d8f2213f60b8cc, 0x49b23f9f6802ed8c86d7ea1efedf0cdf743a07852fac20a6b03808786dcfd856, 0xbe2cdf80d8655a2b4c73a61f1d694e76e351b2d6bed89e14209dd096c54368e3, 0x9cd75fb049720ada50676cae679eb0cd49fb3906bfcb29cdadb2c920b9df2399, 0x1b884bc50314fff026b831a49b989bfa2b191ba2a058f3c8e626ba15b19a4f6d, 0x7c9c8edc1d5782a79065dbb5e8de8d82f1f7e0106c39222cb826f60d2d566f63, 0x28c23ffa8ae9eb6e751a75e29c11321db64a560eb75eca1a1cb86dd353e86441, 0x6a289e986ebd20cfaad165b6167a99ff6ce4af1fe8760b1f773a5ae613a42c23, 0x169f956aa91bb621f6f3acddf8ba6f29a03be60e92988f6af44b902185c5c4b, 0x187aad07f5c0edcd783c16a5ae5a30af712f4b0d4901868b3e9bce0d23eb5401, 0xb99969e6209364cde50284b9fc49d860000010aacceb1640492755addd84f0c7, 0xd25e57f548940d785b2cd275e3a0e1fd7c41bebd45aac794ec09f8b66a34ff5a, 0x22698fcdd44ff0d983f7c90f6715b2a7dbd47b2bffd181eeb820f570acb5c5bd, 0xbe579e6fe757b3aa5e437ad3501393a8078653e6c05c84931e7d650e3f4f0a90, 0x3087502cb0686cc6b2281c8bc0c469aef265f544b9e97d6878fb0390853e3130, 0x8507410f174f5a8d6486fc9c7845cfa3f48ee1030b9ea80e313d3dd31ace5bd4, 86733029210407590466399380249462969730416779574785394407093589143347735943893, 0xf406985113a76e8ff9cbd826fd4735ed00cf370c7bd7ee724d139ddda40888f6, 0x663e881698d916a7ad94c29c09a75111fb5ab141093bf9c6670643c4f7f549cd, 0x14dda320ec07aa3de5e8f0b2a36b1b472630a7ab54724e7af7bddb73401528f8, 0xfb6f1fad9057c6e5c418de49ca948beb0994dadd625dd4b4221d182ce688b4a1, 0xcaaf4c04df50d6f17aa313b7c09af2a90c412c5a6915df3b335c00dce645b8dd, 0x1acdebe1a4577906d3a937b5b6ebe9d27f1b8cb01afbbbfbcc3df9b632c6bedd, 0x1f44bc0cd37a7d328c3181193daac4cc9747740d1fb9eadcfff9b63dfc5e79b4, 0x4d005ecbd8c0c2f76c3a385f8743c9ada8e174bc8e7756c58c9bce8d6d584345, 0x4fece43ec03d5cb2c5c434d1b773aeec1e10d85c2a61f2a084b05f3cd8c02dce, 0x75221369eb7f55f1f856dcfe4d58c96bce2492716e436ed03a7c30441f056973, 0x8197252b5316fe5a10aa9e54d02fb4441b53517cb4f57f4fb0a9d13d36aed797, 0x726859bb2b51da666c59741676b0b42793eb03ed398ed510917d8b03312df2af, 0xff69820ef167a400ffc9ea98b980884cee387a8452441cb273876b4f64073aa9, 0xc6b077e4a962bbd824f0071044349e8e9bcb6cca45bc54e7535d8979f6cfea6c, 0x9ed9a6a8cb737c89fbe150378330f6c8c6e3563ed800871baf369f2af297c660, 0x921832a5f7f05c7c24187afbae3094079650e46191cc15295fa217bd19f8ab8, 0x710829d4583dd6a606a34b9b69de09de49a37225dd3305759c2b6a168d7a0bdf, 0x8978f8a5004be5970a613a1485f4929e79753175075d00a4669aec57356a6e9e, 0x98a7b93d35402471ed9c0e18c874a844d6f81fe16862ee277cb5fd4a8c3c7fe5, 0x5d86416e36ad23e2e4f138c90e5b742629eda088448ce0442703e2ed6e17baf1, 0x808331cf516df155d27cca14d5d5569f85b63f980000381d122ac1c7b9573865, 0xf65fbb497197aef37e016b6c68c42c3a606b73ce0bba94066b8f31e9d4c40733, 0x39583f73e3b4a481b70e3f8637d6f9f3e7e39adee9c8f7a747f23651514abfea, 0xa71b6033653e8128e31b9353098b2297d3808904195fcac753be48ea2e611063, 0x8407a229e3331bafa84bbaf68c24ea710572b300e4e0fcaf37135cce2b7d682, 0x8372118d9eb8e59f8f742a696ded915fe4b5f0aed920f0fe81f20f45b726a33f, 0x8e36c84fc298faa1000000000000000000000000000000000000000000000000]

/-- Corrupt twin: one byte (high byte of a WOTS chain word in layer-0, sig
relative offset 1952) flipped. -/
def calldataWordsCorrupt : List Nat := [0xffb422c71ab92bcfcf2e43999b07fe5900000000000000000000000000000000, 0xd8139d907726d4207397effbef3ada3d00000000000000000000000000000000, 0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef, 0x80, 0xe68, 0x38eb4ba2b366484e681ff7d9703676e34e4837bbbd1285513f29fbcd0b5ea067, 0xfa85eaa528129b23af50176afdc37c5cbdf5ef23805c9692a2a662c1d264b0ce, 0xc0e8c618d040768c02e285583dc14faa972ecb0dc38c5cd43626452243998267, 0x31129b68e74213601d8da2b6c3e7fd5dbf90f308adae12d6a52c3f08dbe9c76f, 0xe1c14d227df5ee57094e69b9ff23ae032d99e89393032320bc96ae065b95ff76, 0xd8b187d501e054360246175ea78e9889cf4fa7b1e3226049fdb853d238a6bf01, 0x8723bf7e254bbdfe61bf7e952467abb74d6eb46cc9c49a55e33181bb987206e, 0x750a3a687319e002f73d2e54511b40d169aef1bb81d004295428f91829ece2cd, 0x6e792d38931bfddd876df9d653bee304918bc601831172c83da9ff5332da9b5, 0xd85444016fb0fe287eec1f23a9dea1d13b5d3ac9f7fafe74e6a66e5222c3b220, 0xd974477df06920ed591dbec00153c0a9c13a0d7b5dcb5fc2c678d6ed5755134, 0x15882f096794a428089a4f64149bfdf9fd5921e352416159c73a920437a042b5, 0x651ddad6e6975566748a25fbd3836c57bf116e54150a4bf3c9a273c9f0d34fcb, 0x53a7919d230e80e23f20de7ae04cc3c4ed5d9ff59b7e0ffaf26a7ed91df163d, 0x3d7414e682581eb62d71a477dbf220c29fb65c85d8c4f3202389f8c78c882915, 0xef448391e893e9fca1ce990df25abe69839c36ee8fd750a3a4de9a69d7a9a6cc, 0x4080802068b497a1cabf5e28b0410cdcc035a5678ddd4e828834d78af7547012, 0x77cce5618ace6c46f65a5aa1f98fdcc8aea6a9f5f5e0de32c4dd4b0df6db5f14, 0xb109cad83f43f6e595f122b78c9cde187e5701cf1d75e815586068e1d190c0cf, 0xaae81d9f8c8e057d756c8336ac267cc91a4581480d6a84bccbffcdef7d3a16b4, 0xe39a1388055eb927c234828b08bc2b99bc5f90e040b67b8669804bcb6af76a99, 0xffc72ef23cd6f602c4c4842f2374950b2d2ce613077e1942bee36c4ec568f463, 0x6ae046b393a2718a4c6376cc54f006edfbcc23f5e1cd242b467ef41f5b8e151b, 0x21b3d9e2f40afe39ddfa4750b01f62863e42c0a95fea87f3595b216d92e29401, 0xfda546898925d69e5b98d8d3d701ad99ad6d980a790d464733d1bfc7fc39bc6a, 0x646d34e822062225006f57bbcf834cbf2042627412fdbf2d5ede8a326b656863, 0x2196bcc97a7381bb428ccc5f162124f439eefa9dcbf92d6fd61bf2a464a71ec8, 0x32ce168fc98d49dcb7fd892a3c821cca92d6a63776480a53a2b4cbb7fd48d701, 0xf7ee11f23a7858eb52ac15e2c84b9c27b644e689d3e43474ea5c926ae579b8d8, 5853871822476609041752857861034802209071191889193637778748703024455873036719, 0x143a85379c1e218eb65ea9528b5d5cb8b42f939a61ce27bea260737e447345eb, 0xdfa61bd8cbf5d3ee4343721fe558fcb32b93c5d071c53509eed8b64b4a7f147a, 0x4f398eeca573db696b70bc0479b32b5cb01f16a13ae8b344d71b659e07b8ef7b, 0xc4c3681ce56a98035692fb3317ff30ab5d56df1133756a685114e6beade4606e, 0xaa7e42d8f0c9d537a9022620be9297a7bac58bb439cddd21595ff02ddca86ca3, 0xeae92a7fc70b58bbf8e3ed6e87170eee136f4d670f150666212e4783938324f9, 0x6b2b7d0041b4dc699c6ea3378ee6bc93d941e8aebbb029024ba276771591424, 0xc774289197dabe12b78900e79ec6e64fc917d73a636828cedd18d73a623a5cf5, 0xb5c425b5faf5c68a915b609cb9b74e822859b8dc65f08c9083e2be6540425fdd, 0xa3704c806ccee2536f23ea0d95830332283db96bca5c0dbe1be99e65ba97768a, 0x5ddbf74e8a04e0ca185987e87e684c7dc56c6addf45d777476e31a67687e7336, 0xbe51aa6e76cc5f37521573a6d00f1185ad45f8f2ed3a8c7c9ad09dca7f73269a, 0xc5c2eb9e2f1b775bbb8494d5ef8a37505d0096ba629103e5b3fb5fa35bd2d8c7, 0xcb43d7a61c5f3ccd1ad63ddd112fc10f1d3cb14cb47a9f80f8a3c8b3f024d636, 0x7cd44b64dcb7541abe8c4d318428a75cd3edd4fd805603e83127df5c44ea96e6, 0x989cb9f1a09f7e3d90e4967470fbdf60686c73f83f6529c3219134981880a58c, 0xb8c4bdbe5d2d59cbd05bffa391cff7ee3c642e7827b21aa8d298ec1dc633d99d, 0xb14bb64dc350136c841da8041a3750b5aa0626e1dc7826c2d966421c47c150e6, 0xa821bc10a133aceddc6cf4717c33716b07d990a284a2728138ab5b6004b4a77d, 0xdb9800ab9dcd1be6585ee0fa055cca087013d53d7c050a89522760c5101e509d, 0x1594ebc7091ce2ec1bcf9e97aae13053eab40e1f235bfe08ee81e666f91d6950, 0x1140f89648832b4515ccd0f345bbb7218ae1aec26110af13f25bc5c8ff9baac1, 0xc29bc37f7c933e405981ccd218b7e6531eba2db7d5ace5d9d6f49f0f0fe3a7c6, 0xd9c3d152bfa88858a8f1f4576f05874f65a985b4a9df7e30b012587f90fed9ca, 0x62c7ee1322c55edd12eb5448410171c3f0ad29a762c4a287ca6f0a81a12b9088, 0xc72ae5ba8f14df01cee870eec67bb20d2bf94ff53eee8d5b3dacd9ef92c95b3d, 0x4ccfb0319fefc0b4c3be24656ce8e691a4b84124bcfc97621028d55041253fbd, 0xc0876f9e3b2dff92beba08cbedc8a4ee8499c385830e7f3095efcc9d7ce7c558, 0x54bd0ca9d84f9966d614942f3f0ebba7175829ed021e14e38e4210afee750c57, 0xe336743cd3b238805f4cdae66dbf370f570fb0fa766cd20d630f1142aa1d711d, 0xf3e3c3b8155abb8c1c918b367a6179c813a1b46b4c76c134bf346a89498fb7e9, 0x71075ad4d3f94c4f140cd4188ff241409a3dc54d05e1b6a1bb0f0ad25b327907, 0x4e8b0d05365b807de157bfeb4d7451cf632917ea1dd7ed631acad795cd19f6f8, 0x45e546e8016c56baa5d9410aad09174792525b637f7bcf01f25abf9f1c7d48e7, 0x2d02d091f0ef3737174841619a870ae5b1b655faba40900ac0a8ccbf1a049dd, 0x2f96327b38b706af5f5fd484efc9bf9bd385f0079a0846e11b73a54ae9ab2b61, 0x61361c2bf132ed09b1b1d01d447fd547c9e75709ac8b2aa51b0cd4cf81814576, 0x2eb4b5752cea83d66da07050cd8c1a29327f37d84881b349a28fc502e6218ec2, 0x76e1c8af14bc4e6e42b8f436a2946a09a2d13a6e8a07a43f3d67ad8a836732f7, 0xadce7b8160668dc0918c083b54a69454b7fc8ef33049be0445ed14c072421aaf, 0x6dcd49b5c6150a2f16e0fb23120148d4fb61c79e7272bc41a2113f682b07fa6d, 0x49d13424512e9f6e6ff26347018b03c0f6a66d5db3ac00531910b609cd599749, 0xfc4c634909fd239bb867e06fb386859c533669fb526b6b7d26d8f2213f60b8cc, 0x49b23f9f6802ed8c86d7ea1efedf0cdf743a07852fac20a6b03808786dcfd856, 0xbe2cdf80d8655a2b4c73a61f1d694e76e351b2d6bed89e14209dd096c54368e3, 0x9cd75fb049720ada50676cae679eb0cd49fb3906bfcb29cdadb2c920b9df2399, 0x1b884bc50314fff026b831a49b989bfa2b191ba2a058f3c8e626ba15b19a4f6d, 0x7c9c8edc1d5782a79065dbb5e8de8d82f1f7e0106c39222cb826f60d2d566f63, 0x28c23ffa8ae9eb6e751a75e29c11321db64a560eb75eca1a1cb86dd353e86441, 0x6a289e986ebd20cfaad165b6167a99ff6ce4af1fe8760b1f773a5ae613a42c23, 0x169f956aa91bb621f6f3acddf8ba6f29a03be60e92988f6af44b902185c5c4b, 0x187aad07f5c0edcd783c16a5ae5a30af712f4b0d4901868b3e9bce0d23eb5401, 0xb99969e6209364cde50284b9fc49d860000010aacceb1640492755addd84f0c7, 0xd25e57f548940d785b2cd275e3a0e1fd7c41bebd45aac794ec09f8b66a34ff5a, 0x22698fcdd44ff0d983f7c90f6715b2a7dbd47b2bffd181eeb820f570acb5c5bd, 0xbe579e6fe757b3aa5e437ad3501393a8078653e6c05c84931e7d650e3f4f0a90, 0x3087502cb0686cc6b2281c8bc0c469aef265f544b9e97d6878fb0390853e3130, 0x8507410f174f5a8d6486fc9c7845cfa3f48ee1030b9ea80e313d3dd31ace5bd4, 86733029210407590466399380249462969730416779574785394407093589143347735943893, 0xf406985113a76e8ff9cbd826fd4735ed00cf370c7bd7ee724d139ddda40888f6, 0x663e881698d916a7ad94c29c09a75111fb5ab141093bf9c6670643c4f7f549cd, 0x14dda320ec07aa3de5e8f0b2a36b1b472630a7ab54724e7af7bddb73401528f8, 0xfb6f1fad9057c6e5c418de49ca948beb0994dadd625dd4b4221d182ce688b4a1, 0xcaaf4c04df50d6f17aa313b7c09af2a90c412c5a6915df3b335c00dce645b8dd, 0x1acdebe1a4577906d3a937b5b6ebe9d27f1b8cb01afbbbfbcc3df9b632c6bedd, 0x1f44bc0cd37a7d328c3181193daac4cc9747740d1fb9eadcfff9b63dfc5e79b4, 0x4d005ecbd8c0c2f76c3a385f8743c9ada8e174bc8e7756c58c9bce8d6d584345, 0x4fece43ec03d5cb2c5c434d1b773aeec1e10d85c2a61f2a084b05f3cd8c02dce, 0x75221369eb7f55f1f856dcfe4d58c96bce2492716e436ed03a7c30441f056973, 0x8197252b5316fe5a10aa9e54d02fb4441b53517cb4f57f4fb0a9d13d36aed797, 0x726859bb2b51da666c59741676b0b42793eb03ed398ed510917d8b03312df2af, 0xff69820ef167a400ffc9ea98b980884cee387a8452441cb273876b4f64073aa9, 0xc6b077e4a962bbd824f0071044349e8e9bcb6cca45bc54e7535d8979f6cfea6c, 0x9ed9a6a8cb737c89fbe150378330f6c8c6e3563ed800871baf369f2af297c660, 0x921832a5f7f05c7c24187afbae3094079650e46191cc15295fa217bd19f8ab8, 0x710829d4583dd6a606a34b9b69de09de49a37225dd3305759c2b6a168d7a0bdf, 0x8978f8a5004be5970a613a1485f4929e79753175075d00a4669aec57356a6e9e, 0x98a7b93d35402471ed9c0e18c874a844d6f81fe16862ee277cb5fd4a8c3c7fe5, 0x5d86416e36ad23e2e4f138c90e5b742629eda088448ce0442703e2ed6e17baf1, 0x808331cf516df155d27cca14d5d5569f85b63f980000381d122ac1c7b9573865, 0xf65fbb497197aef37e016b6c68c42c3a606b73ce0bba94066b8f31e9d4c40733, 0x39583f73e3b4a481b70e3f8637d6f9f3e7e39adee9c8f7a747f23651514abfea, 0xa71b6033653e8128e31b9353098b2297d3808904195fcac753be48ea2e611063, 0x8407a229e3331bafa84bbaf68c24ea710572b300e4e0fcaf37135cce2b7d682, 0x8372118d9eb8e59f8f742a696ded915fe4b5f0aed920f0fe81f20f45b726a33f, 0x8e36c84fc298faa1000000000000000000000000000000000000000000000000]

def sigDataOffset : Nat := 164  -- real EVM sig.offset = 4 + 32*5

/-- Build the RuntimeState: bind the three params + the two ABI locals, and
install the calldata image. memory starts all-zero (matches EVM). -/
def mkState (cd : List Nat) : RuntimeState :=
  { world := { Verity.defaultState with
                 calldata := cd
                 calldataSize := (4 + cd.length * 32 : Nat)
                 memory := fun _ => 0 }
    bindings :=
      bindValue (bindValue (bindValue (bindValue (bindValue []
        "pkSeed" pkSeed) "pkRoot" pkRoot) "message" message)
        "sig_length" 3688) "sig_data_offset" sigDataOffset
    selector := 0 }

def stateAccept  : RuntimeState := mkState calldataWords
def stateCorrupt : RuntimeState := mkState calldataWordsCorrupt

/-- Map a StmtResult to the task's Option Bool: `.return 1`→some true,
`.return 0`→some false, `.revert`→none, anything else→none. -/
def resultToBool : StmtResult → Option Bool
  | .return v _ => some (v != 0)
  | _ => none

/-- Run the FULL compiled body on a state and extract the boolean. -/
def runFull (st : RuntimeState) : Option Bool :=
  resultToBool (execStmtList [] st c13VerifyBody)

/-! ### Sanity probes on the interpreter / state wiring -/

-- params resolve
#eval evalExpr [] stateAccept (.param "pkSeed")        -- expect some pkSeed
#eval evalExpr [] stateAccept (.param "message")       -- expect some message
#eval lookupValue stateAccept.bindings "sig_length"    -- expect 3688
#eval lookupValue stateAccept.bindings "sig_data_offset" -- expect 164

-- R = calldataload(sigBase) & N_MASK : the FIRST (32-aligned) sig read.
-- sigBase=164 -> (164-4)/32 = 5 -> word 5 = sig[0:32]; top half = sig[0:16].
#eval evalExpr [] stateAccept (.calldataload (.param "sig_data_offset"))
-- expect some 0x38eb4ba2b366484e681ff7d9703676e3...(full 32B word)

-- A 16-byte-MISALIGNED sig read the model performs: secretVal i=0 at
-- sigBase+16 = 180 -> (180-4)/32 = 5.5 -> NOT aligned. `calldataloadWord` is now
-- EVM-faithful byte-addressed (Calldata.lean): it stitches word q hi-bits with
-- word q+1 lo-bits, so this returns the REAL sig[16:48], NOT 0. (The old
-- word-aligned-only behaviour returned 0; that divergence is GONE.)
#eval evalExpr [] stateAccept (.calldataload (.add (.param "sig_data_offset") (.literal 16)))
-- expect some <sig[16:48]> (nonzero) — confirms byte-addressed calldata read

/-! ### Full-body execution -/

#eval runFull stateAccept    -- ACCEPT case
#eval runFull stateCorrupt   -- CORRUPT case

end SphincsMinusVerifiers.Preflight

/-! ### Divergence localisation: run a PREFIX of the body and inspect status -/
namespace Probe
open Compiler.CompilationModel
open Compiler.Proofs.IRGeneration.SourceSemantics
open SphincsMinusVerifiers
open SphincsMinusVerifiers.Preflight
def runPrefix (st : RuntimeState) (n : Nat) : StmtResult :=
  execStmtList [] st (c13VerifyBody.take n)
def status : StmtResult → String
  | .continue _ => "continue"
  | .stop _ => "stop"
  | .return v _ => s!"return {v}"
  | .revert => "REVERT"
-- body length
#eval c13VerifyBody.length
-- Walk prefixes: find the first n where status becomes REVERT.
#eval (List.range (c13VerifyBody.length+1)).filterMap (fun n =>
  let s := status (runPrefix stateAccept n)
  if s = "REVERT" then some (n, s) else none) |>.take 3
-- Inspect the digest + the forced-zero guard intermediate (statements 0..13).
-- Show digest and the and(shr(114,dVal),0x7FFFF) the guard tests.
#eval match runPrefix stateAccept 10 with   -- after digest letVar (idx 9 = digest)
  | .continue s => (lookupValue s.bindings "digest", lookupValue s.bindings "htIdx")
  | _ => (0,0)

/-! Pinpoint within statement 25 (the forEach layer loop). On the ACCEPT vector
EVERY prefix `continue`s and the full body returns `some true` (no revert): the
byte-addressed calldata read makes the misaligned WOTS sig reads correct, so the
WOTS+C digitSum guard passes. On the CORRUPT vector the layer-1 grinding guard
(`digitSum == 208`) fails -> REVERT at prefix 26 (inside the layer loop); the
spec's `foldHypertree` returns `.reverted` -> `verifyBytes = none`, so model and
spec AGREE on the corrupt input. -/
-- prefix 25 = everything up to but NOT including the layer loop: should continue
#eval status (runPrefix stateAccept 25)
-- forced-zero guard test value: and(shr(114, digest), 0x7FFFF) (should be 0 to pass)
#eval match runPrefix stateAccept 12 with
  | .continue s =>
      let d := lookupValue s.bindings "dVal"
      (Verity.Core.Uint256.and (Verity.Core.Uint256.shr 114 d) 0x7FFFF).val
  | _ => 999999
-- currentNode (forsPk) entering the layer loop vs the real pkRoot
#eval match runPrefix stateAccept 22 with
  | .continue s => lookupValue s.bindings "currentNode"
  | _ => 0

/-! Corrupt-case divergence: classify the full-length result and find the first
prefix where the corrupt run leaves `continue`. Tells us whether corrupt rejects
by returning 0 (faithful) or by REVERT (possible model/verifyBytes divergence). -/
#eval status (runPrefix stateCorrupt c13VerifyBody.length)
#eval (List.range (c13VerifyBody.length+1)).filterMap (fun n =>
  let s := status (runPrefix stateCorrupt n)
  if s ≠ "continue" then some (n, s) else none) |>.take 5

end Probe
